import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Player de vídeo Luis Izaías com NextJs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head> 
          <link rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" 
            integrity="sha512-..." 
            crossOrigin="anonymous" 
            referrerPolicy="no-referrer" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}